"""
Task model for the Core CLI Todo Application.

This module defines the Task entity as a dataclass with fields for id, title,
description, and completion status. The model is designed to be extensible
for future phases (priorities, due dates, recurrence, tags).
"""

from dataclasses import dataclass, asdict
from typing import Dict, Any


@dataclass
class Task:
    """
    Represents a todo item with unique ID, title, optional description, and completion status.

    Attributes:
        id: Unique sequential integer identifier (auto-generated by TaskService)
        title: Required main task description
        description: Optional additional task details (default: empty string)
        completed: Boolean completion status (default: False/pending)
    """
    id: int
    title: str
    description: str = ""
    completed: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert Task instance to dictionary for serialization (future JSON API).

        Returns:
            Dictionary with id, title, description, completed fields
        """
        return asdict(self)

    def __str__(self) -> str:
        """
        Human-readable string representation for CLI display.

        Returns:
            Formatted string: "Task #<id>: <title> [<status>]"
        """
        status = "completed" if self.completed else "pending"
        return f"Task #{self.id}: {self.title} [{status}]"
